# Generated by Django 4.2.21 on 2025-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_endpoint', models.URLField()),
                ('token_endpoint', models.URLField()),
                ('user_endpoint', models.URLField()),
                ('jwks_endpoint', models.URLField()),
                ('client_id', models.CharField(max_length=48)),
                ('client_secret_cipher', models.BinaryField()),
                ('sign_algo', models.CharField(choices=[('HS256', 'HS256'), ('RS256', 'RS256'), ('ES256', 'ES256')], default='RS256', max_length=5)),
                ('scopes', models.CharField(default='openid profile email phone groups', max_length=250)),
                ('domain', models.CharField(max_length=48, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
