# Generated by Django 4.2.21 on 2025-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federatedprovider',
            name='client_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='genericprovider',
            name='client_id',
            field=models.CharField(max_length=250),
        ),
    ]
