# Generated by Django 4.2.21 on 2025-06-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedauth', '0002_alter_federatedprovider_client_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FederatedProvider',
            new_name='DynamicProvider',
        ),
        migrations.RenameModel(
            old_name='GenericProvider',
            new_name='StaticProvider',
        ),
    ]
